# Generated by Django 5.0.1 on 2024-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='id',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='comment',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
