# Generated by Django 5.0.1 on 2024-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_remove_contactus_id_alter_contactus_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
